apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: my-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-container
        image: subbaraju7899/kubernetes:$BUILD_NUMBER
        ports:
        - containerPort: 8080


---
apiVersion: v1
kind: Service 
metadata: 
  name: springboot-k8ssvc
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - nodePort: 30163
      port: 8080 
      targetPort: 8080
